// CpuOpcodes.js

// Interrups
var CPU_INTS = {
  NMI:   { 'id': 0, 'addr': 0xFFFA },
  RESET: { 'id': 1, 'addr': 0xFFFC },
  IRQ:   { 'id': 2, 'addr': 0xFFFE },
  BRK:   { 'id': 3, 'addr': 0xFFFE },  // not interrupt but instruction
};


// Instructions
var CPU_INSTRUCTIONS = {
  INV: { 'id': 0, 'name': 'inv' }, // Invalid
  ADC: { 'id': 1, 'name': 'adc' },
  AND: { 'id': 2, 'name': 'and' },
  ASL: { 'id': 3, 'name': 'asl' },
  BCC: { 'id': 4, 'name': 'bcc' },
  BCS: { 'id': 5, 'name': 'bcs' },
  BEQ: { 'id': 6, 'name': 'beq' },
  BIT: { 'id': 7, 'name': 'bit' },
  BMI: { 'id': 8, 'name': 'bmi' },
  BNE: { 'id': 9, 'name': 'bne' },
  BPL: { 'id': 10, 'name': 'bpl' },
  BRK: { 'id': 11, 'name': 'brk' },
  BVC: { 'id': 12, 'name': 'bvc' },
  BVS: { 'id': 13, 'name': 'bvs' },
  CLC: { 'id': 14, 'name': 'clc' },
  CLD: { 'id': 15, 'name': 'cld' },
  CLI: { 'id': 16, 'name': 'cli' },
  CLV: { 'id': 17, 'name': 'clv' },
  CMP: { 'id': 18, 'name': 'cmp' },
  CPX: { 'id': 19, 'name': 'cpx' },
  CPY: { 'id': 20, 'name': 'cpy' },
  DEC: { 'id': 21, 'name': 'dec' },
  DEX: { 'id': 22, 'name': 'dex' },
  DEY: { 'id': 23, 'name': 'dey' },
  EOR: { 'id': 24, 'name': 'eor' },
  INC: { 'id': 25, 'name': 'inc' },
  INX: { 'id': 26, 'name': 'inx' },
  INY: { 'id': 27, 'name': 'iny' },
  JMP: { 'id': 28, 'name': 'jmp' },
  JSR: { 'id': 29, 'name': 'jsr' },
  LDA: { 'id': 30, 'name': 'lda' },
  LDX: { 'id': 31, 'name': 'ldx' },
  LDY: { 'id': 32, 'name': 'ldy' },
  LSR: { 'id': 33, 'name': 'lsr' },
  NOP: { 'id': 34, 'name': 'nop' },
  ORA: { 'id': 35, 'name': 'ora' },
  PHA: { 'id': 36, 'name': 'pha' },
  PHP: { 'id': 37, 'name': 'php' },
  PLA: { 'id': 38, 'name': 'pla' },
  PLP: { 'id': 39, 'name': 'plp' },
  ROL: { 'id': 40, 'name': 'rol' },
  ROR: { 'id': 41, 'name': 'ror' },
  RTI: { 'id': 42, 'name': 'rti' },
  RTS: { 'id': 43, 'name': 'rts' },
  SBC: { 'id': 44, 'name': 'sbc' },
  SEC: { 'id': 45, 'name': 'sec' },
  SED: { 'id': 46, 'name': 'sed' },
  SEI: { 'id': 47, 'name': 'sei' },
  STA: { 'id': 48, 'name': 'sta' },
  STX: { 'id': 49, 'name': 'stx' },
  STY: { 'id': 50, 'name': 'sty' },
  TAX: { 'id': 51, 'name': 'tax' },
  TAY: { 'id': 52, 'name': 'tay' },
  TSX: { 'id': 53, 'name': 'tsx' },
  TXA: { 'id': 54, 'name': 'txa' },
  TXS: { 'id': 55, 'name': 'txs' },
  TYA: { 'id': 56, 'name': 'tya' }
};

// Addressing modes

var CPU_ADDRESSINGS = {
  IMMEDIATE: { 'id': 0, 'pc': 2, 'name': 'immediate' },
  ABSOLUTE: { 'id': 1, 'pc': 3, 'name': 'absolute' },
  INDEXED_ABSOLUTE_X: { 'id': 2, 'pc': 3, 'name': 'indexed_absolute_x' },
  INDEXED_ABSOLUTE_Y: { 'id': 3, 'pc': 3, 'name': 'indexed_absolute_y' },
  ZERO_PAGE: { 'id': 4, 'pc': 2, 'name': 'zero_page' },
  INDEXED_ZERO_PAGE_X: { 'id': 5, 'pc': 2, 'name': 'indexed_zero_page_x' },
  INDEXED_ZERO_PAGE_Y: { 'id': 6, 'pc': 2, 'name': 'indexed_zero_page_y' },
  IMPLIED: { 'id': 7, 'pc': 1, 'name': 'implied' },
  ACCUMULATOR: { 'id': 8, 'pc': 1, 'name': 'accumulator' },
  INDIRECT: { 'id': 9, 'pc': 3, 'name': 'indirect' },
  INDEXED_INDIRECT_X: { 'id': 10, 'pc': 2, 'name': 'indexed_indirect_x' },
  INDEXED_INDIRECT_Y: { 'id': 11, 'pc': 2, 'name': 'indexed_indirect_y' },
  RELATIVE: { 'id': 12, 'pc': 2, 'name': 'relative' }
};

// Operations (the combinations of interuction and addressing mode)
// Decoding in advance because it's much easier than implementing decoder.
var CPU_OPS = {
  0x00: { 'instruction': CPU_INSTRUCTIONS.BRK, 'cycle': 7, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x01: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0x02: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x03: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x04: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x05: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x06: { 'instruction': CPU_INSTRUCTIONS.ASL, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x07: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x08: { 'instruction': CPU_INSTRUCTIONS.PHP, 'cycle': 3, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x09: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0x0A: { 'instruction': CPU_INSTRUCTIONS.ASL, 'cycle': 2, 'mode': CPU_ADDRESSINGS.ACCUMULATOR },
  0x0B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x0C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x0D: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x0E: { 'instruction': CPU_INSTRUCTIONS.ASL, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x0F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x10: { 'instruction': CPU_INSTRUCTIONS.BPL, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0x11: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0x12: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x13: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x14: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x15: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x16: { 'instruction': CPU_INSTRUCTIONS.ASL, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x17: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x18: { 'instruction': CPU_INSTRUCTIONS.CLC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x19: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0x1A: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x1B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x1C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x1D: { 'instruction': CPU_INSTRUCTIONS.ORA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x1E: { 'instruction': CPU_INSTRUCTIONS.ASL, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x1F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x20: { 'instruction': CPU_INSTRUCTIONS.JSR, 'cycle': 0, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x21: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0x22: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x23: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x24: { 'instruction': CPU_INSTRUCTIONS.BIT, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x25: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x26: { 'instruction': CPU_INSTRUCTIONS.ROL, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x27: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x28: { 'instruction': CPU_INSTRUCTIONS.PLP, 'cycle': 4, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x29: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0x2A: { 'instruction': CPU_INSTRUCTIONS.ROL, 'cycle': 2, 'mode': CPU_ADDRESSINGS.ACCUMULATOR },
  0x2B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x2C: { 'instruction': CPU_INSTRUCTIONS.BIT, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x2D: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x2E: { 'instruction': CPU_INSTRUCTIONS.ROL, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x2F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x30: { 'instruction': CPU_INSTRUCTIONS.BMI, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0x31: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0x32: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x33: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x34: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x35: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x36: { 'instruction': CPU_INSTRUCTIONS.ROL, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x37: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x38: { 'instruction': CPU_INSTRUCTIONS.SEC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x39: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0x3A: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x3B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x3C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x3D: { 'instruction': CPU_INSTRUCTIONS.AND, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x3E: { 'instruction': CPU_INSTRUCTIONS.ROL, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x3F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x40: { 'instruction': CPU_INSTRUCTIONS.RTI, 'cycle': 6, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x41: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0x42: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x43: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x44: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x45: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x46: { 'instruction': CPU_INSTRUCTIONS.LSR, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x47: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x48: { 'instruction': CPU_INSTRUCTIONS.PHA, 'cycle': 3, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x49: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0x4A: { 'instruction': CPU_INSTRUCTIONS.LSR, 'cycle': 2, 'mode': CPU_ADDRESSINGS.ACCUMULATOR },
  0x4B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x4C: { 'instruction': CPU_INSTRUCTIONS.JMP, 'cycle': 0, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x4D: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x4E: { 'instruction': CPU_INSTRUCTIONS.LSR, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x4F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x50: { 'instruction': CPU_INSTRUCTIONS.BVC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0x51: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0x52: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x53: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x54: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x55: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x56: { 'instruction': CPU_INSTRUCTIONS.LSR, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x57: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x58: { 'instruction': CPU_INSTRUCTIONS.CLI, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x59: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0x5A: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x5B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x5C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x5D: { 'instruction': CPU_INSTRUCTIONS.EOR, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x5E: { 'instruction': CPU_INSTRUCTIONS.LSR, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x5F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x60: { 'instruction': CPU_INSTRUCTIONS.RTS, 'cycle': 6, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x61: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0x62: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x63: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x64: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x65: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x66: { 'instruction': CPU_INSTRUCTIONS.ROR, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x67: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x68: { 'instruction': CPU_INSTRUCTIONS.PLA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x69: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0x6A: { 'instruction': CPU_INSTRUCTIONS.ROR, 'cycle': 2, 'mode': CPU_ADDRESSINGS.ACCUMULATOR },
  0x6B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x6C: { 'instruction': CPU_INSTRUCTIONS.JMP, 'cycle': 0, 'mode': CPU_ADDRESSINGS.INDIRECT },
  0x6D: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x6E: { 'instruction': CPU_INSTRUCTIONS.ROR, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x6F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x70: { 'instruction': CPU_INSTRUCTIONS.BVS, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0x71: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0x72: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x73: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x74: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x75: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x76: { 'instruction': CPU_INSTRUCTIONS.ROR, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x77: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x78: { 'instruction': CPU_INSTRUCTIONS.SEI, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x79: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0x7A: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x7B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x7C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x7D: { 'instruction': CPU_INSTRUCTIONS.ADC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x7E: { 'instruction': CPU_INSTRUCTIONS.ROR, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x7F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x80: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x81: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0x82: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x83: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x84: { 'instruction': CPU_INSTRUCTIONS.STY, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x85: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x86: { 'instruction': CPU_INSTRUCTIONS.STX, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0x87: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x88: { 'instruction': CPU_INSTRUCTIONS.DEY, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x89: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x8A: { 'instruction': CPU_INSTRUCTIONS.TXA, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x8B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x8C: { 'instruction': CPU_INSTRUCTIONS.STY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x8D: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x8E: { 'instruction': CPU_INSTRUCTIONS.STX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0x8F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x90: { 'instruction': CPU_INSTRUCTIONS.BCC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0x91: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0x92: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x93: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x94: { 'instruction': CPU_INSTRUCTIONS.STY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x95: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0x96: { 'instruction': CPU_INSTRUCTIONS.STX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_Y },
  0x97: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0x98: { 'instruction': CPU_INSTRUCTIONS.TYA, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x99: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0x9A: { 'instruction': CPU_INSTRUCTIONS.TXS, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0x9B: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x9C: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x9D: { 'instruction': CPU_INSTRUCTIONS.STA, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0x9E: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0x9F: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xA0: { 'instruction': CPU_INSTRUCTIONS.LDY, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xA1: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0xA2: { 'instruction': CPU_INSTRUCTIONS.LDX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xA3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xA4: { 'instruction': CPU_INSTRUCTIONS.LDY, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xA5: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xA6: { 'instruction': CPU_INSTRUCTIONS.LDX, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xA7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xA8: { 'instruction': CPU_INSTRUCTIONS.TAY, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xA9: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xAA: { 'instruction': CPU_INSTRUCTIONS.TAX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xAB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xAC: { 'instruction': CPU_INSTRUCTIONS.LDY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xAD: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xAE: { 'instruction': CPU_INSTRUCTIONS.LDX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xAF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xB0: { 'instruction': CPU_INSTRUCTIONS.BCS, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0xB1: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0xB2: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xB3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xB4: { 'instruction': CPU_INSTRUCTIONS.LDY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xB5: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xB6: { 'instruction': CPU_INSTRUCTIONS.LDX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_Y },
  0xB7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xB8: { 'instruction': CPU_INSTRUCTIONS.CLV, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xB9: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0xBA: { 'instruction': CPU_INSTRUCTIONS.TSX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xBB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xBC: { 'instruction': CPU_INSTRUCTIONS.LDY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xBD: { 'instruction': CPU_INSTRUCTIONS.LDA, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xBE: { 'instruction': CPU_INSTRUCTIONS.LDX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0xBF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xC0: { 'instruction': CPU_INSTRUCTIONS.CPY, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xC1: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0xC2: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xC3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xC4: { 'instruction': CPU_INSTRUCTIONS.CPY, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xC5: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xC6: { 'instruction': CPU_INSTRUCTIONS.DEC, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xC7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xC8: { 'instruction': CPU_INSTRUCTIONS.INY, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xC9: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xCA: { 'instruction': CPU_INSTRUCTIONS.DEX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xCB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xCC: { 'instruction': CPU_INSTRUCTIONS.CPY, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xCD: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xCE: { 'instruction': CPU_INSTRUCTIONS.DEC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xCF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xD0: { 'instruction': CPU_INSTRUCTIONS.BNE, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0xD1: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0xD2: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xD3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xD4: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xD5: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xD6: { 'instruction': CPU_INSTRUCTIONS.DEC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xD7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xD8: { 'instruction': CPU_INSTRUCTIONS.CLD, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xD9: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0xDA: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xDB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xDC: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xDD: { 'instruction': CPU_INSTRUCTIONS.CMP, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xDE: { 'instruction': CPU_INSTRUCTIONS.DEC, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xDF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xE0: { 'instruction': CPU_INSTRUCTIONS.CPX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xE1: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_X },
  0xE2: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xE3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xE4: { 'instruction': CPU_INSTRUCTIONS.CPX, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xE5: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 3, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xE6: { 'instruction': CPU_INSTRUCTIONS.INC, 'cycle': 5, 'mode': CPU_ADDRESSINGS.ZERO_PAGE },
  0xE7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xE8: { 'instruction': CPU_INSTRUCTIONS.INX, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xE9: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMMEDIATE },
  0xEA: { 'instruction': CPU_INSTRUCTIONS.NOP, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xEB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xEC: { 'instruction': CPU_INSTRUCTIONS.CPX, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xED: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xEE: { 'instruction': CPU_INSTRUCTIONS.INC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.ABSOLUTE },
  0xEF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xF0: { 'instruction': CPU_INSTRUCTIONS.BEQ, 'cycle': 2, 'mode': CPU_ADDRESSINGS.RELATIVE },
  0xF1: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 5, 'mode': CPU_ADDRESSINGS.INDEXED_INDIRECT_Y },
  0xF2: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xF3: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xF4: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xF5: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xF6: { 'instruction': CPU_INSTRUCTIONS.INC, 'cycle': 6, 'mode': CPU_ADDRESSINGS.INDEXED_ZERO_PAGE_X },
  0xF7: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },

  0xF8: { 'instruction': CPU_INSTRUCTIONS.SED, 'cycle': 2, 'mode': CPU_ADDRESSINGS.IMPLIED },
  0xF9: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_Y },
  0xFA: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xFB: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xFC: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null },
  0xFD: { 'instruction': CPU_INSTRUCTIONS.SBC, 'cycle': 4, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xFE: { 'instruction': CPU_INSTRUCTIONS.INC, 'cycle': 7, 'mode': CPU_ADDRESSINGS.INDEXED_ABSOLUTE_X },
  0xFF: { 'instruction': CPU_INSTRUCTIONS.INV, 'cycle': 0, 'mode': null }
}  ;

export { CPU_INTS, CPU_OPS };